yaml

diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -31,28 +31,31 @@ jobs:
       - name: Clean Build
         run: dotnet clean
 
-      # Delete old TestResults directory
-      - name: Clean TestResults
-        run: |
-          if [ -d "./TestResults" ]; then
-            rm -rf ./TestResults
-          fi
-
       # Build tests
       - name: Build Tests
         run: dotnet build tests/ReferenceManager.Tests/ReferenceManager.Tests.csproj
 
       - name: Run tests with coverage
         run: |
+          mkdir -p ./TestResults
           dotnet test tests/ReferenceManager.Tests/ReferenceManager.Tests.csproj \
           -p:CollectCoverage=true \
           -p:CoverletOutputFormat=cobertura \
           -p:CoverletOutput=./TestResults/coverage.cobertura.xml \
-          --results-directory ./TestResults \
           --diag:TestExecution.log
 
       - name: Inspect TestResults Directory
         run: ls -R ./TestResults
+
+      - name: Locate Coverage File
+        run: |
+          coverage_file=$(find ./TestResults -name 'coverage.cobertura.xml' | head -n 1)
+          if [ -z "$coverage_file" ]; then
+            echo "Coverage file not found!"
+            exit 1
+          fi
+          echo "Found coverage file at $coverage_file"
+          echo "COVERAGE_FILE=$coverage_file" >> $GITHUB_ENV
 
       # Run Python script to generate badge
       - name: Generate Coverage Badge
